### ISSUE TITLE
Package MicroDrop plugins as conda packages

### ISSUE THREAD

**Issue by ryanfobel** [wheeler-microfluidics/microdrop#216]
## Motivation

We currently rely on custom code for installing, upgrading and managing MicroDrop plugins and their dependencies. In addition, we cannot support inter-plugin dependencies and have to maintain our own [plugin update server](https://github.com/wheeler-microfluidics/microdrop___plugin_repository).

Sometimes installing a plugin can break a MicroDrop installation either because of the plugin code itself or because of one of its dependencies (e.g., installed via pip).

## Advantages

 * Automatic dependency management
 * Facilitate rollback #200
 * Allow us to leverage [custom conda channels](http://conda.pydata.org/docs/custom-channels.html) as plugin update servers

## Disadvantages:

Probably the biggest disadvantage is that it would be more difficult to install plugins in a non-conda-based Python environment. It could be done, but we would be giving up a lot of the advantages mentioned above.

## Implementation details

Plugins could be stored in the conda environment (e.g., "library/share/MicroDrop plugins"). Simply changing the MicroDrop config should allow plugins to be loaded from this directory.

This change would also require changes to the [Plugin manager](https://github.com/wheeler-microfluidics/microdrop/blob/dev/microdrop/gui/plugin_manager_controller.py) for installing/updating plugins and will likely require writing a `conda-helpers` package for interfacing with conda command-line tools from MicroDrop.

**Comment by cfobel** [comment]
# Proposed implementation

Plugins stored in Conda environment

 1. New plugins bundled as Conda packages **MUST** install to:

       <conda prefix>/share/microdrop/plugins/<plugin name>

 2. Legacy and/or development plugins **MAY** install to:

       <conda prefix>/etc/microdrop/plugins/available/<plugin name>

 3. Plugins installed using **(1)** or **(2)** linked in the following directory **MUST** be **enabled**:

       <conda prefix>/etc/microdrop/plugins/enabled/

## Supporting legacy MicroDrop plugins ##

Legacy MicroDrop plugins **MAY** be made **available** by linking according to **(2)** above.

# TODO #

 - [ ] Create Python API for MicroDrop plugins to:
     * [ ] Query available plugin packages based on specified Conda channels
     * [ ] Install plugin package(s) from selected Conda channels
     * [ ] Uninstall plugin package(s) from selected Conda channels
         * Remove broken links in `<conda prefix>/etc/microdrop/plugins/enabled/`
     * [ ] Update installed plugin package(s) from selected Conda channels
     * [ ] Enable/disable installed plugin package(s)
     * [ ] **Save restore point** after each **install** operation
       ```python
       # Perform installation
       ....
       # Get list of revisions to Conda environment since creation.
       revisions_js = ch.conda_exec('list', '--revisions', '--json', verbose=False)
       revisions = json.loads(revisions_js)
       # Save list of revisions to `<conda prefix>/etc/microdrop/plugins/restore_points/r<revision>.json`
       ...
       ```
     * [ ] **Rollback** (i.e., load last revision number from latest `<conda prefix>/etc/microdrop/plugins/restore_points/r<revision>.json` and run `conda install --revision <revision number>`)

 - [ ] Modify the [Plugin manager][1], providing UI to:
     * [ ] Select Conda channels to search for available MicroDrop plugin packages (default: [`microdrop-plugins`][2]
     * [ ] List available MicroDrop plugin packages from selected channels
       ```python
           import json
           import conda_helpers as ch

           # Get dictionary of available packages
           pkgs_js = ch.conda_exec('search', '--override-channels', '--json', '-c', 'wheeler-microfluidics', verbose=False)
           # Each key in `pkgs` dictionary corresponds to a package name.
           # Each value in `pkgs` dictionary corresponds to a `list` of dictionaries, 
           # each corresponding to an available version of the respective package.
           pkgs = json.loads(pkgs_js)
       ```
     * [ ] Install selected MicroDrop plugin package(s) from list of available packages
     * [ ] Enable/disable installed plugin package(s)
     * [ ] Rollback latest plugin package(s) installation
    
[1]: https://github.com/wheeler-microfluidics/microdrop/blob/dev/microdrop/gui/plugin_manager_controller.py
[2]: https://anaconda.org/microdrop-plugins
